apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j465c5q7k-java-quarkus
  janus-idp.io/tekton: j465c5q7k-java-quarkus
  backstage.io/kubernetes-id: j465c5q7k-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: j465c5q7k-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
